parameters:
    biber_ltd_exception.email.from: support@biberltd.com
    biber_ltd_exception.email.to: support@biberltd.com

#services:
#    biber_ltd_exception.exception_adapter:
#        class: BiberLtd\Bundle\ExceptionBundle\Services\ExceptionAdapter
#        arguments: []